// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAENFLfsqVP8fb4gmeDSseU4RSFDlw5GfI',
    appId: '1:764778069641:web:6136672aa6ef233f725058',
    messagingSenderId: '764778069641',
    projectId: 'authngobeck',
    authDomain: 'authngobeck.firebaseapp.com',
    storageBucket: 'authngobeck.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlpykViL8XNe7bXyOUG3rVsHw2GghWYg4',
    appId: '1:764778069641:android:2b4b567482299efd725058',
    messagingSenderId: '764778069641',
    projectId: 'authngobeck',
    storageBucket: 'authngobeck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOsc6ijdL5YWN_pp1GzY6Yzj0L5BEs2Zk',
    appId: '1:764778069641:ios:01a0695a9539fedd725058',
    messagingSenderId: '764778069641',
    projectId: 'authngobeck',
    storageBucket: 'authngobeck.appspot.com',
    iosBundleId: 'com.ngobeck.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOsc6ijdL5YWN_pp1GzY6Yzj0L5BEs2Zk',
    appId: '1:764778069641:ios:b63c0807efc95b28725058',
    messagingSenderId: '764778069641',
    projectId: 'authngobeck',
    storageBucket: 'authngobeck.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAENFLfsqVP8fb4gmeDSseU4RSFDlw5GfI',
    appId: '1:764778069641:web:37ed6392abe0763d725058',
    messagingSenderId: '764778069641',
    projectId: 'authngobeck',
    authDomain: 'authngobeck.firebaseapp.com',
    storageBucket: 'authngobeck.appspot.com',
  );
}
